### ISSUE TITLE
DMP peer review

### ISSUE THREAD

**Issue by dvasques83** [UOA-MEDSCI-736/Adamthe1st-green-cortex#11]
Hi Ahmed, 

I'm sorry it took me so long to take a look at the your DMP.
It seems that many fields are completed and the file is almost ready to go. Some of my observations:

1- Are you planning to write your related policies?
2- In storage location, perhaps would be nice to point out in which Google Drive and gitHub account you will keep the data.

Try to put some effort on those green annotations of yours :)
Almost there! Well done!

Cheers,

Demi.

**Comment by Adamthe1st** [comment]
Hello Demi, 

Thank you so much for your feedback on my DMP, I have now updated my DMP as per your suggestions. 
Please feel free to check it out on my repository here and close the issue once you are pleased. 

https://github.com/UOA-MEDSCI-736/Adamthe1st-green-cortex

Cheers and good luck for your final assignment! 
Adam

**Comment by dvasques83** [comment]
Very nice!
I'll be closing this issue.
Good luck!

Cheers,
Demi
