### ISSUE TITLE
Peer review of basic_functions.py

### ISSUE THREAD

**Issue by nbir012** [UOA-MEDSCI-736/Adamthe1st-green-cortex#4]
Hey Adam,

*I like that you have put the python version at the top - I'm going to start doing that as well as some code works in one but not the other.
*For the package name you could put in what that package does e.g. openpyxl allows python to open/read excel files.
*The notes on what the file_name string represents might be too much information as the name makes sense (I can guess that file_name means to put in the filename) - having said that, I have been doing commenting on stuff like this myself as I'm still learning and it helps me to understand what variables are required. You probably don't need to change anything now but in the future you might not need to go into so much detail. 
*Checking the file to see whether the file name/cell range is empty is a great idea (i might use it my self!) you could maybe use ''return None-file_name'' and ''return None-cell_range'' as this will give you more info when you quickly glance at it.
*Overall I think your code looks good. You could maybe put a blurb at the top stating how this file fits into your big picture. 

Awesome job - good luck!

Neil

**Comment by Adamthe1st** [comment]
Dear Neil, 

Thank you so much for your great feedback. I will sure use the tips you gave me to further improve my code. I like your suggestion about the "return Non-file_name and cell_range"! I will definitely update my code to cover this point. As for the notes, yes it helped me understand the code when I look at it few days after writing it! However, I am getting used to it slowly and the amount of notes is hopefully decreasing :)

I am glad you found some of my code useful Neil. Lets keep up the good work man!

**Comment by Adamthe1st** [comment]
Dear Neil, 

*I am still working out how to improve the code to return "None-cell_range , None-cell_name" instead of "None" alone. Perhaps I will get my mentor to help me with this one. Ill get back to you once it has been updated.

Nonetheless, I have made the other changes you have suggested and made a pull request. Please feel free to review the changes in (source/basic_functions.py) and close the issue, or raise another if you may. 

Cheers 
Ahmed

**Comment by nbir012** [comment]
Awesome, good stuff and good luck with the final project
